@endpoint = https://j37275erc2.execute-api.eu-west-1.amazonaws.com/prod


GET {{endpoint}}/hello/
###

POST {{endpoint}}/spaces/
Content-Type: application/json
    
    {
        "name": "London Space",
        "description": "My Space Description",
        "location": "London"
    }
###