@endpoint = https://j37275erc2.execute-api.eu-west-1.amazonaws.com/prod


GET {{endpoint}}/hello/
###


GET {{endpoint}}/spaces
###

GET {{endpoint}}/spaces?spaceId=66664854-9d65-4f92-a0bd-99e950b44375
###




GET {{endpoint}}/spaces?location=London
###

POST {{endpoint}}/spaces/
Content-Type: application/json
    
    {
        "name": "London Space",
        "description": "My Space Description",
        "location": "London"
    }
###